export const BOOKING_SAVE_DRIVER_DETAILS = 'BOOKING_SAVE_DRIVER_DETAILS'
export const BOOKING_SAVE_PAYMENT_METHOD = 'BOOKING_SAVE_PAYMENT_METHOD'

export const BOOKING_SAVE_VEHICLE_DETAILS = 'BOOKING_SAVE_VEHICLE_DETAILS'
