export const BOOKING_SAVE_DRIVER_DETAILS = 'BOOKING_SAVE_DRIVER_DETAILS'
export const BOOKING_SAVE_PAYMENT_METHOD = 'BOOKING_SAVE_PAYMENT_METHOD'

export const BOOKING_SAVE_VEHICLE_DETAILS = 'BOOKING_SAVE_VEHICLE_DETAILS'

export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST'
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS'
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL'
