export const VEHICLE_LIST_REQUEST = 'VEHICLE_LIST_REQUEST'
export const VEHICLE_LIST_SUCCESS = 'VEHICLE_LIST_SUCCESS'
export const VEHICLE_LIST_FAIL = 'VEHICLE_LIST_FAIL'

export const VEHICLE_DETAILS_REQUEST = 'VEHICLE_DETAILS_REQUEST'
export const VEHICLE_DETAILS_SUCCESS = 'VEHICLE_DETAILS_SUCCESS'
export const VEHICLE_DETAILS_FAIL = 'VEHICLE_DETAILS_FAIL'

export const VEHICLE_DELETE_REQUEST = 'VEHICLE_DELETE_REQUEST'
export const VEHICLE_DELETE_SUCCESS = 'VEHICLE_DELETE_SUCCESS'
export const VEHICLE_DELETE_FAIL = 'VEHICLE_DELETE_FAIL'
