export const VEHICLE_LIST_REQUEST = 'VEHICLE_LIST_REQUEST'
export const VEHICLE_LIST_SUCCESS = 'VEHICLE_LIST_SUCCESS'
export const VEHICLE_LIST_FAIL = 'VEHICLE_LIST_FAIL'

export const VEHICLE_DETAILS_REQUEST = 'VEHICLE_DETAILS_REQUEST'
export const VEHICLE_DETAILS_SUCCESS = 'VEHICLE_DETAILS_SUCCESS'
export const VEHICLE_DETAILS_FAIL = 'VEHICLE_DETAILS_FAIL'

export const VEHICLE_DELETE_REQUEST = 'VEHICLE_DELETE_REQUEST'
export const VEHICLE_DELETE_SUCCESS = 'VEHICLE_DELETE_SUCCESS'
export const VEHICLE_DELETE_FAIL = 'VEHICLE_DELETE_FAIL'

export const VEHICLE_CREATE_REQUEST = 'VEHICLE_CREATE_REQUEST'
export const VEHICLE_CREATE_SUCCESS = 'VEHICLE_CREATE_SUCCESS'
export const VEHICLE_CREATE_FAIL = 'VEHICLE_CREATE_FAIL'
export const VEHICLE_CREATE_RESET = 'VEHICLE_CREATE_RESET'

export const VEHICLE_UPDATE_REQUEST = 'VEHICLE_UPDATE_REQUEST'
export const VEHICLE_UPDATE_SUCCESS = 'VEHICLE_UPDATE_SUCCESS'
export const VEHICLE_UPDATE_FAIL = 'VEHICLE_UPDATE_FAIL'
export const VEHICLE_UPDATE_RESET = 'VEHICLE_UPDATE_RESET'

export const VEHICLE_CREATE_REVIEW_REQUEST = 'VEHICLE_CREATE_REVIEW_REQUEST'
export const VEHICLE_CREATE_REVIEW_SUCCESS = 'VEHICLE_CREATE_REVIEW_SUCCESS'
export const VEHICLE_CREATE_REVIEW_FAIL = 'VEHICLE_CREATE_REVIEW_FAIL'
export const VEHICLE_CREATE_REVIEW_RESET = 'VEHICLE_CREATE_REVIEW_RESET'

export const VEHICLE_TOP_REQUEST = 'VEHICLE_TOP_REQUEST'
export const VEHICLE_TOP_SUCCESS = 'VEHICLE_TOP_SUCCESS'
export const VEHICLE_TOP_FAIL = 'VEHICLE_TOP_FAIL'
